### ISSUE TITLE
[埔里 || 遠端工作] 何六百徵求全端網站工程師一名

### ISSUE THREAD

**Issue by ho600** [TechBridgeWeekly/jobs#3]
- **職缺名稱（job title）：** 全端網站工程師(目前工作內容主要為「 **Django** 後端程式開發」)
- **公司/團隊簡介（company/team description）：** 何六百有限公司的經營理念為「在合法的前提下，謀求股東、員工、客戶利益的最佳平衡點」，服務目標則為「將現實世界映射在 0 與 1 的網路,求解後供人們作對的事。」
- **職缺工作內容描述（job description）：** 敝公司目前主要營運模式為接案公司，提供業主完整的資訊系統開發、維運服務及任何難題諮詢。代管之系統除 Open Source 軟體外，餘為敝公司協助業主客製化之系統。目前代管系統如下：

    - 任務追蹤系統
    - 文件管理系統
    - 內容管理系統
    - 電商銷售系統
    - 電子報收發系統
    - 信用卡支付系統

    伺服器皆置於雲端平台，主要是 Amazon AWS 及 Google App Engine 。

    工作角色分為三大部份： 系統管理員(DevOps)、後端程式開發員、前端設計師。每一員工皆需擔任此三角色，也就是所謂的「全能工班(營建業術語: Full-Capacity Operation) || 網站全端工程師(軟體業術語: Full Stack Web Engineer)」，惟其工作比例可有不一，目前 **重點徵求後端程式開發員** ，實際工作內容比例約為 10% DevOps 、 70% 後端開發 、 20% 前端開發。

    在溝通語言及文件寫作上，主要使用中華民國國語，次要使用英文，少部份使用日文。其他請詳閱 https://jobs.ho600.com/#workload 
- **職缺工作地點（job location）：** 埔里或遠端工作，但遠端工作地點仍需位於中華民國實際管轄境內，且須具備或可申請 5M/sec 以上之網路(含3G/4G電信上網)
- **職缺工作能力要求（skill requirements）：** 完全 **不在意你的家庭背景、學經歷、工作經驗** 。能通過敝司的考試就有能力，考試流程請見 https://jobs.ho600.com/#flow 
- **薪資範圍（salary range）：** 每月 2.5 萬 ~ 8.5 萬
- **工時/特休（time）：** 每月 160 小時以下，且一律依中華民國國定假日休假
- **應徵聯絡方式（apply contacts）：** 敝司有「公平、可匿名的考試網站」，請直接到 https://jobs.ho600.com/#apply 應聘

（選擇性補充）

- **福利（welfare）：** 一般企業常見的生日禮金、三節禮金、員工旅遊、尾牙抽獎都 **不會有** ，主要原因是敝公司不是「一般企業」，其他福利請見 https://jobs.ho600.com/#salary 。但強調的是，敝司完全遵守就業服務法及勞動基準法，像是: 來敝司上班後，發現工作表現不符公司期待，一定依法資遣。
- **加分項目（bonus）：** 敝司創辦人相信多元、多樣是企業長久營運的必要條件之一，所以只要能通過敝司考試，而其他只要是比敝司創辦人厲害的技能都會加分。例如: 用右手小指按 ＜Tab＞ 鍵的速度比創辦人用左手小指按 ＜Tab＞ 快。
- **團隊技術介紹（tech stack）：** 就一個 **別人都沒有的** 『公平、可匿名考試網站』，敝司可用 AWS Lambda/DynamoDB/S3/API Gateway 及 PGP 建置，而這些不過是敝司常用技術中的一小部份，其他部份歡迎來敝司上班後領略。如果你現在就對『公平、可匿名考試網站』有興趣的話，請到 https://bitbucket.org/ho600/exam-yueh-cake-com/ 看看文件及程式碼。
- **開放、樂分享的工作模式：** 詳見敝司的公開文件集 http://ho600.readthedocs.io/

**Comment by u8621011** [comment]
不得不說一下，「公平、可匿名的考試網站」非常有趣的模式。

**Comment by owlfox** [comment]
真的很有趣，不過
若成功完成徵才，請記得請同仁回來把 issue 關掉，謝謝！

**Comment by ho600** [comment]
感謝 @owlfox 。我疏忽了。
